server:
  port: 8030



# git管理配置
spring:
  application:
    name: service-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JoinMaZhe/spring-cloud-study/ #git仓库地址  //仓库为公共是用户名密码配置失效，无拦截
          search-paths:                           # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 1457492126@qq.com
          password: mz433157